### ISSUE TITLE
Facing issue while running yarn start --oss

### ISSUE THREAD

**Issue by pushkarva** [guyplusplus/Kibana-Plugin-Custom-Form-Filter-Visualization#1]
Facing issue while running yarn start --oss
Any help would be appreciated:

 ERROR in ./public/custom_form_filter_accounts_vis.tsx
       │          Module not found: Error: import [../../../src/plugins/vis_default_editor/public] references a public export of the [visDefaultEditor] bundle, but that bundle is not in the "requiredPlugins" or "requiredBundles" list in the plugin manifest [/Users/A398199/Documents/elastic/kibana/plugins/vis_type_custom_form_filter_accounts/kibana.json]
       │           @ ./public/custom_form_filter_accounts_vis.tsx 21:0-83 52:19-36
       │           @ ./public/plugin.ts
       │           @ ./public/index.ts
       │           @ /Users/A398199/Documents/elastic/kibana/packages/kbn-optimizer/target/worker/entry_point_creator.js

**Comment by guyplusplus** [comment]
Interesting...
- Which version of the plugin you have downloaded?
- Which version of Kibana you are using (`git status`)?

**Comment by guyplusplus** [comment]
Found the problem after full rebuilt. Fixed in version 1.0.4

**Comment by pushkarva** [comment]
> Found the problem after full rebuilt. Fixed in version 1.0.4

I was able to figure out the plugin issue

**Comment by guyplusplus** [comment]
Plugin now has issue on 7.12.1 as plugin API has changed (again)... I need to figure out...
